#Dockerfile para temas de desarrollo local (no optimizada para despliegue)
FROM node:22-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
EXPOSE 5173
CMD ["npm", "run", "dev", "--", "--host"]
