# Etapa de build
FROM node:18-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Etapa de producción
FROM node:18-alpine AS prod

WORKDIR /app

COPY --from=build /app/package*.json ./
RUN npm install --omit=dev

COPY --from=build /app/build ./build

# Exponemos el puerto que Railway usará
EXPOSE 3000

# Comando para levantar el servidor Node de SvelteKit
CMD ["node", "build"]
