# Imagen
FROM node:22-alpine

# Directorio de trabajo dentro del contenedor
WORKDIR /app

#Copiamos package.json y package-lock.json
COPY package*.json ./

# Instalamos dependencias
RUN npm install

# Exponemos el puerto de Vite/SvelteKit
EXPOSE 5173

# Comando por defecto: levantar el servidor de desarrollo
CMD ["npm", "run", "dev", "--", "--host"]
